# Welcome to Jekyll!
#
# ì´ ì„¤ì • íŒŒì¼ì€ ì‚¬ì´íŠ¸ ì „ì²´ì— ì˜í–¥ì„ ë¯¸ì¹˜ëŠ” ì„¤ì • ê°’ë“¤ì„ í¬í•¨í•©ë‹ˆë‹¤.
# ì¼ë°˜ì ìœ¼ë¡œ í•œ ë²ˆ ì„¤ì •í•˜ê³  ë‚˜ë©´ ìì£¼ ìˆ˜ì •í•  í•„ìš”ê°€ ì—†ëŠ” ê°’ë“¤ì…ë‹ˆë‹¤.
# ê¸°ìˆ ì ì¸ ì´ìœ ë¡œ, ì´ íŒŒì¼ì€ `jekyll serve`ë¥¼ ì‚¬ìš©í•  ë•Œ ìë™ìœ¼ë¡œ ë‹¤ì‹œ ë¡œë“œë˜ì§€ ì•ŠìŠµë‹ˆë‹¤.
# ì´ íŒŒì¼ì„ ë³€ê²½í•œ í›„ì—ëŠ” ì„œë²„ í”„ë¡œì„¸ìŠ¤ë¥¼ ë‹¤ì‹œ ì‹œì‘í•˜ì‹­ì‹œì˜¤.

# Theme Settings
#
# í…Œë§ˆ ì„¤ì¹˜ ê°€ì´ë“œ: https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
# minimal_mistakes_skin    : # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "sorbetsharkRoundhand ğŸ¦ˆ"
title_separator          : "ìš°ë¦¬ ë¸”ë¡œê·¸ ì •ìƒì˜ì—…í•©ë‹ˆë‹¤."
subtitle                 : "ëˆ„ë•ëˆ„ë• ë¸”ë¡œê·¸"
name                     : "sorbet shark round hand"
description              : "Adorable doguri, Exciting AI."
url                      : "https://sorbetsharkroundhand.github.io"
baseurl                  : # ì‚¬ì´íŠ¸ì˜ ì„œë¸Œ ê²½ë¡œ, ì˜ˆ: "/blog"
repository               : # GitHub ì‚¬ìš©ìëª…/ì €ì¥ì†Œëª…, ì˜ˆ: "mmistakes/minimal-mistakes"
teaser                   : # ê¸°ë³¸ í‹°ì € ì´ë¯¸ì§€ ê²½ë¡œ, ì˜ˆ: "/assets/images/500x300.png"
logo                     : # í—¤ë”ì— í‘œì‹œë  ë¡œê³  ì´ë¯¸ì§€ ê²½ë¡œ, ì˜ˆ: "/assets/images/88x88.png"
masthead_title           : "ìš°ë¦¬ ë¸”ë¡œê·¸ ì •ìƒì˜ì—…í•©ë‹ˆë‹¤" 
# breadcrumbs            : false # true, false (ê¸°ë³¸ê°’)
words_per_minute         : 200 # ë¶„ë‹¹ ì½ê¸° ë‹¨ì–´ ìˆ˜ ì„¤ì •
enable_copy_code_button  : # true, false (ê¸°ë³¸ê°’)
copyright                : # "copyright" ì´ë¦„, ê¸°ë³¸ê°’ì€ site.title
copyright_url            : # "copyright" URL, ê¸°ë³¸ê°’ì€ site.url
comments:
  provider               : # ëŒ“ê¸€ ì œê³µì ì„¤ì •, false (ê¸°ë³¸ê°’), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "giscus", "custom"
  disqus:
    shortname            : # Disqus shortname
  discourse:
    server               : # Discourse ì„œë²„ URL
  facebook:
    appid                :
    num_posts            : # 5 (ê¸°ë³¸ê°’)
    colorscheme          : # "light" (ê¸°ë³¸ê°’), "dark"
  utterances:
    theme                : # "github-light" (ê¸°ë³¸ê°’), "github-dark"
    issue_term           : # "pathname" (ê¸°ë³¸ê°’)
  giscus:
    repo_id              : # giscus ì„¤ì • ì‹œ í‘œì‹œë˜ëŠ” repo_id
    category_name        : # ì¹´í…Œê³ ë¦¬ ì´ë¦„
    category_id          : # giscus ì„¤ì • ì‹œ í‘œì‹œë˜ëŠ” category_id
    discussion_term      : # "pathname" (ê¸°ë³¸ê°’), "url", "title", "og:title"
    reactions_enabled    : # '1' (ê¸°ë³¸ê°’) í™œì„±í™”, '0' ë¹„í™œì„±í™”
    theme                : # "light" (ê¸°ë³¸ê°’), "dark", "dark_dimmed", "transparent_dark", "preferred_color_scheme"
    strict               : # 1 í™œì„±í™”, 0 ë¹„í™œì„±í™” (ê¸°ë³¸ê°’)
    input_position       : # "top", "bottom"
    emit_metadata        : # 1 í™œì„±í™”, 0 ë¹„í™œì„±í™” (ê¸°ë³¸ê°’)
    lang                 : # "en" (ê¸°ë³¸ê°’)
    lazy                 : # true, false
  staticman:
    branch               : # "master"
    endpoint             : # "https://{your Staticman v3 API}/v3/entry/github/"
reCaptcha:
  siteKey                :
  secret                 :
atom_feed:
  path                   : # ë¹ˆ ê°’ (ê¸°ë³¸ê°’) ì‚¬ìš© ì‹œ feed.xml
  hide                   : # true, false (ê¸°ë³¸ê°’)
search                   : # true, false (ê¸°ë³¸ê°’)
search_full_content      : # true, false (ê¸°ë³¸ê°’)
search_provider          : # lunr (ê¸°ë³¸ê°’), algolia, google
lunr:
  search_within_pages    : # true, false (ê¸°ë³¸ê°’)
algolia:
  application_id         : # YOUR_APPLICATION_ID
  index_name             : # YOUR_INDEX_NAME
  search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : # true (ê¸°ë³¸ê°’), false
google:
  search_engine_id       : # YOUR_SEARCH_ENGINE_ID
  instant_search         : # false (ê¸°ë³¸ê°’), true

# SEO ê´€ë ¨ ì„¤ì •
google_site_verification :
bing_site_verification   :
naver_site_verification  :
yandex_site_verification :
baidu_site_verification  :

# ì†Œì…œ ê³µìœ  ì„¤ì •
twitter:
  username               :
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : # Open Graph/Twitter ê¸°ë³¸ ì‚¬ì´íŠ¸ ì´ë¯¸ì§€

# ì†Œì…œ í”„ë¡œí•„ ì§€ì •
social:
  type                   : # Person ë˜ëŠ” Organization (ê¸°ë³¸ê°’ì€ Person)
  name                   : # ì‚¬ìš©ì ë˜ëŠ” ì¡°ì§ ì´ë¦„ì´ ì‚¬ì´íŠ¸ ì´ë¦„ê³¼ ë‹¤ë¥¼ ê²½ìš°
  links: # ì†Œì…œ ë¯¸ë””ì–´ í”„ë¡œí•„ ë§í¬ ë°°ì—´

# ì• ë„ë¦¬í‹±ìŠ¤ ì„¤ì •
analytics:
  provider               : false # false (ê¸°ë³¸ê°’), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          :
    anonymize_ip         : # true, false (ê¸°ë³¸ê°’)

# ì‚¬ì´íŠ¸ ì €ì ì„¤ì •
author:
  name             : "sorbetsharkRoundhand"
  avatar           : # ì•„ë°”íƒ€ ì´ë¯¸ì§€ ê²½ë¡œ, ì˜ˆ: "/assets/images/bio-photo.jpg"
  bio              : "Adorable doguri, Exciting AI."
  location         : "Korea"
  email            :
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      # url: "mailto:your.name@email.com"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      # url: "https://your-website.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      # url: "https://twitter.com/"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url: "https://facebook.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      # url: "https://github.com/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url: "https://instagram.com/"

# ì‚¬ì´íŠ¸ í‘¸í„° ì„¤ì •
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      # url:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      # url:
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      # url:
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
      # url:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url:

# íŒŒì¼ ì½ê¸° ì„¤ì •
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # Minimal Mistakes /docs ë¬´ì‹œ
  - /test # Minimal Mistakes /test ë¬´ì‹œ
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# ë³€í™˜ ì„¤ì •
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown ì²˜ë¦¬ ì„¤ì •
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS ì„¤ì •
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# ì¶œë ¥ ì„¤ì •
permalink: /:categories/:title/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# jekyll-paginate í”ŒëŸ¬ê·¸ì¸ì„ ì‚¬ìš©í•œ í˜ì´ì§€ë„¤ì´ì…˜ ì„¤ì •
paginate: 5 # í‘œì‹œí•  í¬ìŠ¤íŠ¸ ìˆ˜
paginate_path: /page:num/

# jekyll-paginate-v2 í”ŒëŸ¬ê·¸ì¸ì„ ì‚¬ìš©í•œ í˜ì´ì§€ë„¤ì´ì…˜ ì„¤ì •
# ì„¤ì • ìì„¸í•œ ë‚´ìš©: https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md#site-configuration
pagination:
  # v2 ì‚¬ìš© ì„¤ì •
  # enabled: true
  debug: false
  collection: 'posts'
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: ''
  trail:
    before: 2
    after: 2

# í”ŒëŸ¬ê·¸ì¸ ì„¤ì •
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# GitHub Pagesì™€ --safe ì˜µì…˜ì„ ëª¨ë°©
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# ì•„ì¹´ì´ë¸Œ ì„¤ì •
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# jekyll-archives í”ŒëŸ¬ê·¸ì¸ ì„¤ì •
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/

# HTML ì••ì¶• ì„¤ì •
compress_html:
  clippings: all
  ignore:
    envs: development

# ê¸°ë³¸ê°’ ì„¤ì •
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true

# ë„¤ë¹„ê²Œì´ì…˜ ì„¤ì •
navigation:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  # ë‹¤ë¥¸ ë„¤ë¹„ê²Œì´ì…˜ í•­ëª©ë“¤...
